<?php
/**
 * @author: Mihai Petcu mihai.costin.petcu@gmail.com
 * @date: 3.11.2015
 */
class ReportController extends ControllerBase
{
    public function initialize(){
        parent::initialize();
        $this->view->dbs = Db::find(); //list all dbs in the left column
        $this->view->currentDbId = $this->request->get('id');
    }

    /**
     * Show files generated by reports This action will be viewed by
     */
    public function indexAction(){
        $this->view->dbsl = $this->view->dbs;
        $this->view->dbs = false;
    }

    /**
     * Add a report
     * @return mixed
     */
    public function newAction(){
        $db = Db::findById($this->request->get('db'));
        if($this->processForm($db->newReport(), 'ReportForm')){
            $this->flash->success("Report <strong>".$db->name."/".$this->request->get('name')."</strong> was created succesfully.");
            return $this->response->redirect('db/show?id='.$db->getId());
        }
        $this->view->dbm = $db;
    }

    /**
     * Edit a report
     * @return mixed
     */
    public function editAction(){
        $report = Report::findById($this->request->get('id'));
        if($this->processForm($report, 'ReportForm')){
            $this->flash->success("Report <strong>".$report->getDb()->name."/".$this->request->get('name')."</strong> was changed succesfully.");
            return $this->response->redirect('db/show?id='.$report->getDb()->getId());
        }
        $this->view->report = $report;
    }

    /**
     * Remove a report
     * @return mixed
     */
    public function deleteAction(){
        $report = Report::findById($this->request->get('id'));
        if($this->request->get('confirm')) {
            $db = $report->getDb();
            $name = $report->name;
            if ($report->delete()) {
                $this->flash->success("Report <strong>" . $db->name . "/" . $this->request->get('name') . "</strong> was removed succesfully.");
            }
            return $this->response->redirect('db/show?id=' . $db->getId());
        }
        $this->view->report = $report;
    }

    /**
     * The run action called from runModal action.
     * The output is redirected to runModal view
     */
    public function runAction(){
        $report = Report::findById($this->request->get('id'));
        $report->generateFile('user', 'CSV')->save();
        $report->save();

        //send mail
        //$report->sendNotif();

        $this->view->lastRun = true;
        $this->view->report = $report;
        $this->view->pick('report/runModal');
    }

    /**
     * Run manually a database report in a modal
     */
    public function runModalAction(){
        $report = Report::findById($this->request->get('id'));
        $this->view->lastRun = false;
        $this->view->report = $report;
    }

    /**
     * Add/Delete emails modal for sending report notifications
     * @return mixed
     */
    public function msgModalAction(){
        $report = Report::findById($this->request->get('id'));
        if($this->processForm($report, 'MailReportForm')){
            $this->flash->success("Saved succesfully.");
            return $this->response->redirect('report/msgModal?id='.$report->getId());
        }
        $this->view->report = $report;
    }

    /**
     * Add/Edit/Disable cron job modal to a database report
     * @return mixed
     */
    public function jobModalAction(){
        $report = Report::findById($this->request->get('id'));
        $job = $report->getJob();
        if($this->processForm($job, 'JobForm')){
            $this->flash->success("Saved succesfully.");
            return $this->response->redirect('report/jobModal?id='.$report->getId());
        }
        $this->view->report = $report;
        $this->view->job = $job;
    }

    /**
     * Show full logs modal for a report (manually or cron job)
     */
    public function fullLogModalAction(){
        $report = Report::findById($this->request->get('id'));
        $this->view->report = $report;
    }

}

